name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'microservice-1/**'
  pull_request:
    branches: [ main ]

jobs:
  buildms1:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: 'microservice-1'
    
    - name: list
      run: |
        ls -ltr
        cd microservice-1
        ls -ltr

    - name: Install dependencies
      uses: actions/setup-java@v4
      with:
        java-version: '21.0.2' # Specifies the exact Java version
        distribution: 'microsoft'
        cache: 'maven'
    
    - name: Build with Maven
      run: |
        cd microservice-1
        mvn clean install
    
    - name: Run tests
      run: mvn test
    
    - name: Run linting
      run: mvn sonar:sonar
    
  #   - name: Run tests
  #     run: npm test
    
  #   - name: Run linting
  #     run: npm run lint

  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '18'
  #       cache: 'npm'
    
  #   - name: Install dependencies
  #     run: npm ci
    
  #   - name: Build application
  #     run: npm run build
    
  #   - name: Upload build artifacts
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: build-files
  #       path: dist/

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: build-files
  #       path: dist/
    
  #   - name: Deploy to production
  #     run: echo "Deploy to production server"